name: ci

on:
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - name: チェックアウトする
        uses: actions/checkout@v4
      - name: Goの環境をセットアップする
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.1'
      - name: フォーマット実行
        run: test -z $(gofmt -l .)
      - name: 静的解析実行
        run: go vet ./..
      - name: テスト実行
        run: go test
      - name: ビルド実行
        run: go build .
